spring:
  application:
    name: settling-me-softly
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
